/**
 * plugins/vuetify.js
 *
 * Framework documentation: https://vuetifyjs.com`
 */

// Styles
import "@mdi/font/css/materialdesignicons.css";
import "vuetify/styles";

// Composables
import { createVuetify } from "vuetify";
import { VNumberInput } from "vuetify/labs/VNumberInput";

// https://vuetifyjs.com/en/introduction/why-vuetify/#feature-guides
export default createVuetify({
  components: {
    VNumberInput,
  },
  theme: {
    defaultTheme: "dark",
    themes: {
      light: {
        dark: false,
        colors: {
          "primary-palette-key-color": "#0b80f6",
          "secondary-palette-key-color": "#5c78a8",
          "tertiary-palette-key-color": "#be62da",
          "neutral-palette-key-color": "#747780",
          "neutral-variant-palette-key-color": "#717785",
          background: "#f9f9ff",
          "on-background": "#181c23",
          surface: "#f9f9ff",
          "surface-dim": "#d7dae4",
          "surface-bright": "#f9f9ff",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f1f3fd",
          "surface-container": "#ebedf8",
          "surface-container-high": "#e6e8f2",
          "surface-container-highest": "#e0e2ec",
          "on-surface": "#181c23",
          "surface-variant": "#dde2f2",
          "on-surface-variant": "#414754",
          "inverse-surface": "#2d3038",
          "inverse-on-surface": "#eef0fb",
          outline: "#717785",
          "outline-variant": "#c1c6d6",
          shadow: "#000000",
          scrim: "#000000",
          "surface-tint": "#005db7",
          primary: "#005bb3",
          "on-primary": "#ffffff",
          "primary-container": "#d6e3ff",
          "on-primary-container": "#001b3d",
          "inverse-primary": "#a9c7ff",
          secondary: "#425f8e",
          "on-secondary": "#ffffff",
          "secondary-container": "#d6e3ff",
          "on-secondary-container": "#001b3d",
          tertiary: "#8c32a9",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#fbd7ff",
          "on-tertiary-container": "#330044",
          error: "#ba1a1a",
          "on-error": "#ffffff",
          "error-container": "#ffdad6",
          "on-error-container": "#410002",
          "primary-fixed": "#d6e3ff",
          "primary-fixed-dim": "#a9c7ff",
          "on-primary-fixed": "#001b3d",
          "on-primary-fixed-variant": "#00468c",
          "secondary-fixed": "#d6e3ff",
          "secondary-fixed-dim": "#abc7fd",
          "on-secondary-fixed": "#001b3d",
          "on-secondary-fixed-variant": "#294774",
          "tertiary-fixed": "#fbd7ff",
          "tertiary-fixed-dim": "#f0b0ff",
          "on-tertiary-fixed": "#330044",
          "on-tertiary-fixed-variant": "#731491",
        },
        variables: {},
      },
      dark: {
        dark: true,
        colors: {
          "primary-palette-key-color": "#0b80f6",
          "secondary-palette-key-color": "#5c78a8",
          "tertiary-palette-key-color": "#be62da",
          "neutral-palette-key-color": "#747780",
          "neutral-variant-palette-key-color": "#717785",
          background: "#10131a",
          "on-background": "#e0e2ec",
          surface: "#10131a",
          "surface-dim": "#10131a",
          "surface-bright": "#363941",
          "surface-container-lowest": "#0b0e15",
          "surface-container-low": "#181c23",
          "surface-container": "#1c2027",
          "surface-container-high": "#272a31",
          "surface-container-highest": "#31353c",
          "on-surface": "#e0e2ec",
          "surface-variant": "#414754",
          "on-surface-variant": "#c1c6d6",
          "inverse-surface": "#e0e2ec",
          "inverse-on-surface": "#2d3038",
          outline: "#8b919f",
          "outline-variant": "#414754",
          shadow: "#000000",
          scrim: "#000000",
          "surface-tint": "#a9c7ff",
          primary: "#a9c7ff",
          "on-primary": "#003063",
          "primary-container": "#00468c",
          "on-primary-container": "#d6e3ff",
          "inverse-primary": "#005db7",
          secondary: "#abc7fd",
          "on-secondary": "#0e305c",
          "secondary-container": "#294774",
          "on-secondary-container": "#d6e3ff",
          tertiary: "#f0b0ff",
          "on-tertiary": "#54006d",
          "tertiary-container": "#731491",
          "on-tertiary-container": "#fbd7ff",
          error: "#ffb4ab",
          "on-error": "#690005",
          "error-container": "#930009",
          "on-error-container": "#ffb4ab",
          "primary-fixed": "#d6e3ff",
          "primary-fixed-dim": "#a9c7ff",
          "on-primary-fixed": "#001b3d",
          "on-primary-fixed-variant": "#00468c",
          "secondary-fixed": "#d6e3ff",
          "secondary-fixed-dim": "#abc7fd",
          "on-secondary-fixed": "#001b3d",
          "on-secondary-fixed-variant": "#294774",
          "tertiary-fixed": "#fbd7ff",
          "tertiary-fixed-dim": "#f0b0ff",
          "on-tertiary-fixed": "#330044",
          "on-tertiary-fixed-variant": "#731491",
          "on-inverse-primary": "#a9c7ff",
          "primary-fixed-variant": "#d6e3ff",
          "secondary-fixed-variant": "#d6e3ff",
          "tertiary-fixed-variant": "#fbd7ff",
        },
        variables: {},
      },
    },
  },
});
