/**
 * plugins/vuetify.js
 *
 * Framework documentation: https://vuetifyjs.com`
 */

// Styles
import "@mdi/font/css/materialdesignicons.css";
import "vuetify/styles";

// Composables
import { createVuetify } from "vuetify";
import { VNumberInput } from "vuetify/labs/VNumberInput";

// https://vuetifyjs.com/en/introduction/why-vuetify/#feature-guides
export default createVuetify({
  components: {
    VNumberInput,
  },
  theme: {
    themes: {
      light: {
        dark: false,
        colors: {
          "primary-palette-key-color": "#597a97",
          "secondary-palette-key-color": "#6c7885",
          "tertiary-palette-key-color": "#7c5d81",
          "neutral-palette-key-color": "#767779",
          "neutral-variant-palette-key-color": "#72777d",
          background: "#faf9fb",
          "on-background": "#1a1c1e",
          surface: "#faf9fb",
          "surface-dim": "#dadadc",
          "surface-bright": "#faf9fb",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f4f3f6",
          "surface-container": "#eeedf0",
          "surface-container-high": "#e8e8ea",
          "surface-container-highest": "#e3e2e4",
          "on-surface": "#1a1c1e",
          "surface-variant": "#dee3ea",
          "on-surface-variant": "#42474d",
          "inverse-surface": "#2f3033",
          "inverse-on-surface": "#f1f0f3",
          outline: "#73777e",
          "outline-variant": "#c2c7ce",
          shadow: "#000000",
          scrim: "#000000",
          "surface-tint": "#40627d",
          primary: "#31536e",
          "on-primary": "#ffffff",
          "primary-container": "#cce5ff",
          "on-primary-container": "#001e31",
          "inverse-primary": "#a8caea",
          secondary: "#54606c",
          "on-secondary": "#ffffff",
          "secondary-container": "#d7e4f2",
          "on-secondary-container": "#111d27",
          tertiary: "#624568",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#fcd7ff",
          "on-tertiary-container": "#2a1131",
          error: "#ba1a1a",
          "on-error": "#ffffff",
          "error-container": "#ffdad6",
          "on-error-container": "#410002",
          "primary-fixed": "#cce5ff",
          "primary-fixed-dim": "#a8caea",
          "on-primary-fixed": "#001e31",
          "on-primary-fixed-variant": "#284a64",
          "secondary-fixed": "#d7e4f2",
          "secondary-fixed-dim": "#bbc8d6",
          "on-secondary-fixed": "#111d27",
          "on-secondary-fixed-variant": "#3c4853",
          "tertiary-fixed": "#fcd7ff",
          "tertiary-fixed-dim": "#e0bae3",
          "on-tertiary-fixed": "#2a1131",
          "on-tertiary-fixed-variant": "#593d5e",
        },
        variables: {},
      },
      dark: {
        dark: true,
        colors: {
          "primary-palette-key-color": "#597a97",
          "secondary-palette-key-color": "#6c7885",
          "tertiary-palette-key-color": "#7c5d81",
          "neutral-palette-key-color": "#767779",
          "neutral-variant-palette-key-color": "#72777d",
          background: "#121315",
          "on-background": "#e3e2e4",
          surface: "#121315",
          "surface-dim": "#121315",
          "surface-bright": "#38393b",
          "surface-container-lowest": "#0d0e10",
          "surface-container-low": "#1a1c1e",
          "surface-container": "#1e2022",
          "surface-container-high": "#292a2c",
          "surface-container-highest": "#333537",
          "on-surface": "#e3e2e4",
          "surface-variant": "#42474d",
          "on-surface-variant": "#c2c7ce",
          "inverse-surface": "#e3e2e4",
          "inverse-on-surface": "#2f3033",
          outline: "#8c9197",
          "outline-variant": "#42474d",
          shadow: "#000000",
          scrim: "#000000",
          "surface-tint": "#a8caea",
          primary: "#a8caea",
          "on-primary": "#0c334d",
          "primary-container": "#284a64",
          "on-primary-container": "#cce5ff",
          "inverse-primary": "#40627d",
          secondary: "#bbc8d6",
          "on-secondary": "#26323c",
          "secondary-container": "#3c4853",
          "on-secondary-container": "#d7e4f2",
          tertiary: "#e0bae3",
          "on-tertiary": "#412647",
          "tertiary-container": "#593d5e",
          "on-tertiary-container": "#fcd7ff",
          error: "#ffb4ab",
          "on-error": "#690005",
          "error-container": "#930009",
          "on-error-container": "#ffb4ab",
          "primary-fixed": "#cce5ff",
          "primary-fixed-dim": "#a8caea",
          "on-primary-fixed": "#001e31",
          "on-primary-fixed-variant": "#284a64",
          "secondary-fixed": "#d7e4f2",
          "secondary-fixed-dim": "#bbc8d6",
          "on-secondary-fixed": "#111d27",
          "on-secondary-fixed-variant": "#3c4853",
          "tertiary-fixed": "#fcd7ff",
          "tertiary-fixed-dim": "#e0bae3",
          "on-tertiary-fixed": "#2a1131",
          "on-tertiary-fixed-variant": "#593d5e",
          "on-inverse-primary": "#a8caea",
          "primary-fixed-variant": "#cce5ff",
          "secondary-fixed-variant": "#d7e4f2",
          "tertiary-fixed-variant": "#fcd7ff",
        },
        variables: {},
      },
    },
    defaultTheme: "dark",
  },
});
